### PR TITLE
Add support for a Global API key

### PR DESCRIPTION
**Pull request by littleBitsman**
Adds support for a global API key when configuring.
Whenever more services are added, just add `config.ServiceName = config.Global` to the if statement.
Solves #4 
(Very simple way to make this)

### CODE REVIEW

**Comment by littleBitsman** [comment]
For some reason the diff editor says that I modified the export line, but I didn't so ignore it I guess

**Comment by DevAX1T** [comment]
Greetings! I did not expect anyone to make one of these

**Comment by DevAX1T** [comment]
I shall test this just to be safe then approve it if it works. (v2 is still coming soon I swear)

**Review by DevAX1T — APPROVED** [review]
yea no i dont need to test this

**Comment by littleBitsman** [comment]
alright thanks i guess

**Pull request merged**
